<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up(): void {
  Schema::create('kpi_periods', function(Blueprint $t){$t->id();$t->unsignedTinyInteger('bulan');$t->unsignedSmallInteger('tahun');$t->string('status')->default('draft');$t->foreignId('mpa_evaluator_id')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('mpa_assigned_at')->nullable();$t->timestamp('published_at')->nullable();$t->foreignId('published_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();$t->unique(['bulan','tahun']);});
  Schema::create('kpi_participants', function(Blueprint $t){$t->id();$t->foreignId('kpi_period_id')->constrained()->cascadeOnDelete();$t->foreignId('karyawan_id')->constrained('karyawan')->restrictOnDelete();$t->foreignId('jabatan_id')->nullable()->constrained('jabatan')->nullOnDelete();$t->string('jabatan_snapshot');$t->foreignId('departemen_id')->nullable()->constrained('departemen')->nullOnDelete();$t->string('departemen_snapshot')->nullable();$t->foreignId('penempatan_id')->nullable()->constrained('penempatan')->nullOnDelete();$t->string('penempatan_snapshot')->nullable();$t->foreignId('atasan_langsung_id')->nullable()->constrained('karyawan')->nullOnDelete();$t->string('atasan_langsung_snapshot')->nullable();$t->foreignId('atasan_kedua_id')->nullable()->constrained('karyawan')->nullOnDelete();$t->string('atasan_kedua_snapshot')->nullable();$t->string('status')->default('active');$t->unsignedInteger('ops_correction_revision')->default(0);$t->boolean('ops_correction_pending_reapproval')->default(false);$t->foreignId('ops_corrected_by_user_id')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('ops_corrected_at')->nullable();$t->text('ops_correction_reason')->nullable();$t->timestamps();$t->unique(['kpi_period_id','karyawan_id']);});
  Schema::create('kpi_daily_reports', function(Blueprint $t){$t->id();$t->foreignId('karyawan_id')->constrained('karyawan')->restrictOnDelete();$t->date('tanggal');$t->foreignId('approver_id')->nullable()->constrained('karyawan')->nullOnDelete();$t->foreignId('atasan_snapshot_id')->nullable()->constrained('karyawan')->nullOnDelete();$t->string('status')->default('draft');$t->timestamp('submitted_at')->nullable();$t->foreignId('approved_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('approved_at')->nullable();$t->string('approval_source',20)->nullable();$t->string('approval_signature_path')->nullable();$t->timestamps();$t->unique(['karyawan_id','tanggal']);});
  Schema::create('kpi_daily_activities', function(Blueprint $t){$t->id();$t->foreignId('daily_report_id')->constrained('kpi_daily_reports')->cascadeOnDelete();$t->unsignedSmallInteger('urutan');$t->text('rincian_kegiatan');$t->text('keterangan')->nullable();$t->string('bukti_path')->nullable();$t->timestamps();});
  Schema::create('kpi_individual_scores', function(Blueprint $t){$t->id();$t->foreignId('kpi_participant_id')->constrained()->cascadeOnDelete();$t->decimal('capaian_departemen',5,2)->nullable();$t->decimal('perawatan_aset',5,2)->nullable();$t->decimal('kebersihan_kerapihan',5,2)->nullable();$t->text('keterangan_capaian')->nullable();$t->text('keterangan_aset')->nullable();$t->text('keterangan_kebersihan')->nullable();$t->json('parameter_snapshot')->nullable();$t->decimal('score',8,2)->default(0);$t->string('status')->default('draft');$t->boolean('value_locked')->default(false);$t->decimal('corrected_score',8,2)->nullable();$t->unsignedInteger('correction_revision')->default(0);$t->boolean('correction_pending_reapproval')->default(false);$t->foreignId('corrected_by_user_id')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('corrected_at')->nullable();$t->text('correction_reason')->nullable();$t->string('submit_type')->nullable();$t->timestamp('submitted_at')->nullable();$t->timestamps();$t->unique('kpi_participant_id');});
  Schema::create('kpi_ops_items', function(Blueprint $t){$t->id();$t->foreignId('kpi_participant_id')->constrained()->cascadeOnDelete();$t->unsignedSmallInteger('urutan')->default(0);$t->string('kpi_item');$t->text('maintenance')->nullable();$t->decimal('target_unit',12,4);$t->decimal('target_bulanan',12,4)->default(0);$t->unsignedTinyInteger('bulan')->nullable();$t->string('tanda',10)->nullable();$t->decimal('beban_target',12,4)->default(0);$t->string('sumber_data_snapshot');$t->string('frekuensi')->nullable();$t->decimal('hasil',12,4)->nullable();$t->text('aktivitas')->nullable();$t->string('bukti_path')->nullable();$t->decimal('nilai_item',12,4)->default(0);$t->string('status')->default('draft');$t->string('submit_type')->nullable();$t->timestamp('submitted_at')->nullable();$t->timestamps();});
  Schema::create('kpi_monthlies', function(Blueprint $t){$t->id();$t->foreignId('kpi_participant_id')->constrained()->cascadeOnDelete();$t->foreignId('evaluator_id')->nullable()->constrained('users')->nullOnDelete();$t->decimal('kinerja_operasional',5,2)->nullable();$t->decimal('sikap_kerja',5,2)->nullable();$t->decimal('team_work',5,2)->nullable();$t->decimal('inisiatif',5,2)->nullable();$t->decimal('kepemimpinan',5,2)->nullable();$t->decimal('mpa_score',8,2)->default(0);$t->text('performance')->nullable();$t->text('coaching')->nullable();$t->decimal('attendance_score',8,2)->default(0);$t->decimal('reward_punishment_score',8,2)->default(0);$t->string('status')->default('scheduled');$t->timestamp('hrd_initial_completed_at')->nullable();$t->foreignId('hrd_initial_completed_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('evaluator_started_at')->nullable();$t->timestamp('evaluator_completed_at')->nullable();$t->foreignId('evaluator_completed_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('hrd_finalized_at')->nullable();$t->foreignId('hrd_finalized_by')->nullable()->constrained('users')->nullOnDelete();$t->foreignId('takeover_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('takeover_at')->nullable();$t->text('takeover_reason')->nullable();$t->timestamp('completed_at')->nullable();$t->foreignId('completed_by')->nullable()->constrained('users')->nullOnDelete();$t->boolean('late_completed')->default(false);$t->timestamp('published_at')->nullable();$t->foreignId('published_by')->nullable()->constrained('users')->nullOnDelete();$t->boolean('late_published')->default(false);$t->timestamps();$t->unique('kpi_participant_id');});
  Schema::create('kpi_attendance_adjustments', function(Blueprint $t){$t->id();$t->foreignId('monthly_id')->constrained('kpi_monthlies')->cascadeOnDelete();$t->string('kode',4);$t->unsignedInteger('jumlah')->default(0);$t->decimal('nilai',6,2);$t->timestamps();});
  Schema::create('kpi_reward_punishments', function(Blueprint $t){$t->id();$t->foreignId('monthly_id')->constrained('kpi_monthlies')->cascadeOnDelete();$t->string('jenis');$t->unsignedInteger('jumlah')->default(0);$t->decimal('nilai',6,2);$t->timestamps();});
  Schema::create('kpi_signatures', function(Blueprint $t){$t->id();$t->string('signable_type');$t->unsignedBigInteger('signable_id');$t->foreignId('signed_for_user_id')->nullable()->constrained('users')->nullOnDelete();$t->foreignId('signed_by_user_id')->nullable()->constrained('users')->nullOnDelete();$t->string('role');$t->string('source')->default('manual');$t->string('signature_path')->nullable();$t->timestamp('signed_at')->nullable();$t->string('reason')->nullable();$t->timestamps();$t->unique(['signable_type','signable_id','role']);});
  Schema::create('kpi_final_scores', function(Blueprint $t){$t->id();$t->foreignId('kpi_participant_id')->constrained()->cascadeOnDelete();$t->decimal('ki_score',8,2)->default(0);$t->decimal('ops_score',8,2)->default(0);$t->decimal('mpa_score',8,2)->default(0);$t->decimal('attendance_score',8,2)->default(0);$t->decimal('reward_punishment_score',8,2)->default(0);$t->decimal('score',10,2)->default(0);$t->string('kategori');$t->string('status')->default('draft');$t->boolean('late_finalization')->default(false);$t->timestamp('calculated_at')->nullable();$t->timestamps();$t->unique('kpi_participant_id');});
  Schema::create('kpi_audits', function(Blueprint $t){$t->id();$t->foreignId('kpi_period_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('actor_id')->nullable()->constrained('users')->nullOnDelete();$t->string('action');$t->text('reason')->nullable();$t->json('before')->nullable();$t->json('after')->nullable();$t->unsignedInteger('revision')->default(1);$t->timestamps();});
 }
 public function down(): void { foreach(['kpi_audits','kpi_final_scores','kpi_signatures','kpi_reward_punishments','kpi_attendance_adjustments','kpi_monthlies','kpi_ops_items','kpi_individual_scores','kpi_daily_activities','kpi_daily_reports','kpi_participants','kpi_periods'] as $table) Schema::dropIfExists($table); }
};
