<script setup>
import InternalDashboardLayout from '@/Layouts/InternalDashboardLayout.vue';
import KpiEmployeeHeader from '@/Components/Internal/KpiEmployeeHeader.vue';
import KpiEmployeeLayout from '@/Components/Internal/KpiEmployeeLayout.vue';
import { useConfirmation } from '@/composables/useConfirmation';
import { useForm, router } from '@inertiajs/vue3';
import { computed } from 'vue';
const props=defineProps({user:Object,period:Object,participant:Object,score:Object,isWindowAllowed:Boolean,windowState:String,isOwner:Boolean,canApprove:Boolean,approval:Object,employeePeriods:{type:Array,default:()=>[]}});
const confirmation = useConfirmation();
const components=computed(()=>props.score?.parameter_snapshot||[{key:'capaian_departemen',label:'Capaian Departemen',weight:.7,note:'Pencapaian target kerja departemen.'},{key:'perawatan_aset',label:'Perawatan Aset Kerja Sesuai Bidang',weight:.05,note:'Perawatan alat dan aset operasional.'},{key:'kebersihan_kerapihan',label:'Kebersihan & Kerapihan Lingkungan Kerja',weight:.05,note:'Kebersihan dan kerapihan area kerja.'}]);
const form=useForm({capaian_departemen:props.score?.capaian_departemen??null,perawatan_aset:props.score?.perawatan_aset??null,kebersihan_kerapihan:props.score?.kebersihan_kerapihan??null,keterangan_capaian:props.score?.keterangan_capaian??'',keterangan_aset:props.score?.keterangan_aset??'',keterangan_kebersihan:props.score?.keterangan_kebersihan??''});
const values=computed(()=>components.value.map(c=>Number(form[c.key])||0)); const weighted=computed(()=>components.value.map((c,i)=>values.value[i]*Number(c.weight))); const total=computed(()=>weighted.value.reduce((a,b)=>a+b,0).toFixed(2));
const locked=computed(()=>['approved','auto_signed','locked'].includes(props.score?.status)||!props.isWindowAllowed||!props.isOwner); const statusLabel=computed(()=>({draft:'Dalam Pengisian',submitted:'Menunggu Persetujuan',approved:props.approval?.source==='super_admin_takeover'?'Diambil Alih Super Admin':'Disetujui',not_filled:'Tidak Mengisi',auto_signed:'Ditandatangani Otomatis'}[props.score?.status]||'Dalam Pengisian')); const statusClass=computed(()=>({approved:props.approval?.source==='super_admin_takeover'?'bg-emerald-800 text-white':'bg-emerald-100 text-emerald-700',submitted:'bg-amber-100 text-amber-700',not_filled:'bg-rose-100 text-rose-700',auto_signed:'bg-blue-100 text-blue-700'}[props.score?.status]||'bg-slate-100 text-slate-600'));
const months=['Januari','Februari','Maret','April','Mei','Juni','Juli','Agustus','September','Oktober','November','Desember']; const periodLabel=computed(()=>`${months[props.period.bulan-1]} ${props.period.tahun}`); const employee=computed(()=>props.participant?.karyawan||{}); const submit=()=>form.post(route('dashboard.kpi.individual',props.period.id),{preserveScroll:true});
const approve=async()=>{ if(await confirmation.confirm({title:'Tanda Tangani Kinerja Individu?',message:`Anda akan menandatangani dan menyetujui Kinerja Individu milik ${employee.value.nama||'karyawan'} periode ${periodLabel.value}.`,confirmText:'Ya, Tanda Tangani'})) router.post(route('dashboard.kpi.sign'),{signable_type:'kinerja_individu',signable_id:props.score.id,role:'atasan_langsung'},{preserveScroll:true}); };
</script>
<template><InternalDashboardLayout title="Kinerja Individu" :user="user"><KpiEmployeeLayout>
<KpiEmployeeHeader :employee-id="participant.karyawan_id" :period="period" :available-periods="employeePeriods" active-tab="individual" page-title="Kinerja Individu" :status-label="statusLabel" :status-class="statusClass" />
<section class="rounded-xl border border-[#dce5f1] bg-white p-4"><h2 class="text-lg font-bold text-[#102f66]">● Informasi Karyawan</h2><dl class="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div v-for="item in [['Nama',employee.nama||participant.karyawan_snapshot||'-'],['NIK',employee.nik||'-'],['Jabatan',participant.jabatan_snapshot||employee.jabatan?.nama_jabatan||'-'],['Departemen',participant.departemen_snapshot||employee.departemen?.nama_departemen||'-'],['Penempatan',participant.penempatan_snapshot||employee.penempatan?.nama_penempatan||'-'],['Atasan Langsung',participant.atasan_langsung_snapshot||'-'],['Periode',periodLabel]]" :key="item[0]" class="rounded-lg bg-[#f3f6fa] px-3 py-2.5"><dt class="text-[11px] text-[#60749a]">{{item[0]}}</dt><dd class="mt-0.5 text-sm font-semibold text-[#142d5d]">{{item[1]}}</dd></div></dl></section>
<div v-if="windowState==='closed'&&score?.status==='draft'" class="rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-800">Batas normal pengisian telah berakhir.</div>
<section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="flex items-center justify-between border-b border-slate-200 p-6"><div><h2 class="text-lg font-bold text-slate-900">Penilaian Kinerja Individu</h2><p class="mt-1 text-sm text-slate-500">Isi evaluasi diri dengan skala 1–100.</p></div><span class="text-sm font-semibold text-slate-500">Maksimum normal 80.00</span></div><div class="overflow-x-auto"><table class="w-full min-w-[850px] text-left text-sm"><thead class="bg-slate-50 text-xs uppercase text-slate-500"><tr><th class="px-6 py-4">No</th><th class="px-6 py-4">Kontribusi untuk Perusahaan</th><th class="px-6 py-4">Bobot</th><th class="px-6 py-4">Evaluasi Diri</th><th class="px-6 py-4">Nilai Bobot</th><th class="px-6 py-4">Keterangan</th></tr></thead><tbody class="divide-y divide-slate-100"><tr v-for="(c,i) in components" :key="c.key"><td class="px-6 py-4 font-semibold text-slate-500">{{i+1}}</td><td class="px-6 py-4"><p class="font-semibold text-slate-800">{{c.label}}</p><p class="mt-1 text-xs text-slate-500">{{c.note}}</p></td><td class="px-6 py-4 font-semibold text-blue-700">{{(Number(c.weight)*100).toFixed(0)}}%</td><td class="px-6 py-4"><input v-model.number="form[c.key]" type="number" min="1" max="100" :disabled="locked" class="w-24 rounded-lg border-slate-300 text-sm font-semibold disabled:bg-slate-100" placeholder="1–100"></td><td class="px-6 py-4 font-bold text-slate-800">{{weighted[i].toFixed(2)}}</td><td class="px-6 py-4"><input v-model="form[['keterangan_capaian','keterangan_aset','keterangan_kebersihan'][i]]" :disabled="locked" class="w-full min-w-[190px] rounded-lg border-slate-300 text-sm disabled:bg-slate-100" placeholder="Opsional"></td></tr></tbody><tfoot class="bg-blue-50"><tr><td colspan="4" class="px-6 py-4 text-right font-bold text-slate-700">Total Nilai KI</td><td class="px-6 py-4 text-xl font-bold text-blue-700">{{total}}</td><td></td></tr></tfoot></table></div><div v-if="isOwner&&isWindowAllowed&&!locked" class="flex justify-end border-t border-slate-200 p-6"><button @click="submit" :disabled="form.processing" class="rounded-xl bg-blue-600 px-6 py-3 text-sm font-bold text-white hover:bg-blue-700 disabled:opacity-50">{{form.processing?'Menyimpan...':'Simpan Penilaian'}}</button></div></section>
<section v-if="approval||['submitted','approved','auto_signed'].includes(score?.status)" class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div class="flex items-center justify-between"><div><h2 class="text-lg font-bold text-slate-900">Persetujuan Atasan Langsung</h2><p class="text-sm text-slate-500">Status tanda tangan penilaian</p></div><span class="rounded-full px-3 py-1 text-xs font-semibold" :class="approval?.source==='automatic'?'bg-blue-100 text-blue-700':approval?'bg-emerald-100 text-emerald-700':'bg-amber-100 text-amber-700'">{{approval?.source==='automatic'?'Auto Signed':approval?'Disetujui':'Menunggu Persetujuan'}}</span></div><div v-if="!approval&&canApprove&&score?.status==='submitted'" class="mt-4 flex justify-end"><button @click="approve" class="rounded-xl bg-blue-600 px-5 py-2.5 text-sm font-bold text-white hover:bg-blue-700">Tanda Tangani &amp; Setujui</button></div><div v-if="approval" class="mt-5 grid gap-5 md:grid-cols-[1fr_280px]"><div><p class="text-xs uppercase text-slate-500">Disetujui oleh</p><p class="mt-1 text-xl font-bold text-slate-900">{{approval.signer_name||'-'}}</p><p class="text-sm text-slate-500">{{approval.signer_position||'Atasan Langsung'}}</p><p class="mt-4 text-sm text-slate-600">{{approval.source==='automatic'?'Ditandatangani otomatis oleh sistem karena batas waktu berakhir.':'Penilaian telah disetujui dan dikunci.'}}</p></div><div class="rounded-xl border border-slate-200 bg-slate-50 p-4 text-center"><p class="text-xs font-semibold text-slate-500">Tanda Tangan</p><img v-if="approval.signature_url" :src="approval.signature_url" class="mx-auto mt-3 h-24 w-full object-contain" alt="Tanda tangan atasan"><p class="mt-2 text-xs text-slate-500">{{approval.signed_at||'-'}}</p></div></div></section>
</KpiEmployeeLayout></InternalDashboardLayout></template>
